### ISSUE TITLE
Mouse not moving / Thumbsticks are not responding

### ISSUE THREAD

**Issue by Sezei** [Crayon2000/UsendMii-Client#8]
The mouse does not move, but it does in fact register in UsentMii as the c-pad as "active".
Same goes for the Xbox mode (as shown in the picture).

![תמונה](https://user-images.githubusercontent.com/49373598/55687741-1f25da00-5979-11e9-8df7-eb400390fb68.png)

The version is 0.6.1, I am using a new 3ds xl.

**Comment by Crayon2000** [comment]
Hello @greasemonkey123, I don't own a new 3DS. Can you tell me if this version fixes the issue; ~~UsendMii-Test-Fix.zip~~

EDIT: Link was removed, use official version when available

**Comment by Sezei** [comment]
> 
> 
> Hello @greasemonkey123, I don't own a new 3DS. Can you tell me if this version fixes the issue; ~~UsendMii-Test-Fix.zip~~

It fixed the issue of the mouse not moving, but now there's a new issue;
It doesn't connect to XInput as it previously did.

**Comment by Crayon2000** [comment]
When you say 'previously', you mean with UsendMii version 0.6.1? Are the buttons still working with XInput with UsendMii version 0.6.1?

**Comment by Sezei** [comment]
Yes, the buttons still worked with vXbox. Only the thumbsticks didn't.

**Comment by Crayon2000** [comment]
Hello, I just did a quick test with vXbox with my Wii U on my test PC and it seems to work. I know that vXboxInterface had problems with Windows 10 updates (https://github.com/shauleiz/vXboxInterface/issues/7).

Between 0.6.1 and the version I gave you, there is no difference in the XBox code. Maybe it's just because I gave you a Win32 build and your computer / drivers requires a Win64 executable! Can you test this new version: ~~UsendMii-Test-Fix.zip~~

EDIT: Link was removed, use official version when available

**Comment by Sezei** [comment]
![תמונה](https://user-images.githubusercontent.com/49373598/55890790-03f6dc80-5bbc-11e9-8117-7447c1c27fb9.png)
Hello. It looks like this didn't change the problem of not connecting to the XInput anymore, unlike the previous version, which connected to it in the startup of UsendMii.

**Comment by Crayon2000** [comment]
Hello, just to be clear. Did you put the executable file (_UsendMii.exe_) in the same folder as the previous one?

Try this:
1) Rename the old _UsendMii.exe_ file, the one that is working with vXboxInterface, to something else
2) Extract the one from the zip file, _UsendMii-Test-Fix.zip_, in the same folder.

**Comment by Sezei** [comment]
> 
> 
> Hello, just to be clear. Did you put the executable file (_UsendMii.exe_) in the same folder as the previous one?
> 
> Try this:
> 
>     1. Rename the old _UsendMii.exe_ file, the one that is working with vXboxInterface, to something else
> 
>     2. Extract the one from the zip file, _UsendMii-Test-Fix.zip_, in the same folder.

Yes, I have placed it in the same folder as the XInput tester. I'll edit the reply when I'll test the two tips.

EDIT: Still won't work. Sorry to say that.

**Comment by Crayon2000** [comment]
OK, the problem was in fact that you need the 64-bit version of the excutable. For some reason the file did not upload properly, so the second version was the 32-bit version too.

Can you try this one please: [UsendMii-Test-Fix-64.zip](https://github.com/Crayon2000/UsendMii-Client/files/3071423/UsendMii-Test-Fix-64.zip)

Thanks and sorry for wasting your time 😁

**Comment by Sezei** [comment]
> 
> 
> OK, the problem was in fact that you need the 64-bit version of the excutable. For some reason the file did not upload properly, so the second version was the 32-bit version too.
> 
> Can you try this one please: [UsendMii-Test-Fix-64.zip](https://github.com/Crayon2000/UsendMii-Client/files/3071423/UsendMii-Test-Fix-64.zip)
> 
> Thanks and sorry for wasting your time 😁

This fixed the issue. Thank you very much.
